version: '2'

volumes:
  db_test:

services:

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_test:/var/lib/postgresql/data

  db_setup:
    build: db_setup
    depends_on:
      - db

